[master]
  version = 1
  runner = "./bin/ci"
[global]
  PUBLISH_EXECUTABLES = "cinema slideshow"
[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.22.4.0"
[build.dist-7-8]
  GHC_VERSION = "7.8.4"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.9.3"
[build.branches-7-8]
  GHC_VERSION = "7.8.4"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.9.3"
[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.9.3"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  PURESCRIPT_VERSION = "0.9.3"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.9.3"
[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"
  PURESCRIPT_VERSION = "0.9.3"

[build.dist-doc]
  AMBIATA_DOC = "$AMBIATA_DOC_MASTER"
  AMBIATA_DOC_URL = "http://doc.engineering.ambiata.com/master"
  [build.dist-doc.master]
    runner = "./bin/ci.doc"

[build.branches-doc]
  AMBIATA_DOC = "$AMBIATA_DOC_BRANCHES"
  AMBIATA_DOC_URL = "http://doc.engineering.ambiata.com/branches"
  [build.branches-doc.master]
    runner = "./bin/ci.doc"

[build.haskell]
  [build.haskell.master]
    runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20160609072923-58d5481/master-haskell-20160609072923-58d5481"
    sha1 = "f827e1ff43bcaa325d128662391d95a8b4d65525"
